#!/bin/bash

#SBATCH --chdir /home/yinyu/Thesis/animal-reid
#SBATCH --nodes 1
#SBATCH --ntasks 1

#SBATCH --time 30:00:00
#SBATCH --partition gpu

#SBATCH --cpus-per-task 1
#SBATCH --mem 20G
#SBATCH --gres gpu:2


#SBATCH --mail-user=yingxue.yu@epfl.ch 
#SBATCH --mail-type=ALL


#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name swin_triplet_posture_segv3_ls_tiger --batch_size 32 --ent_cls --triplet --triplet_sampler --use_posture --use_swin --lr 0.01 --total_epoch 2   -d 0,1 --data_type tiger  --warm_epoch 3 --label_smoothing >./slurm/swin_triplet_posture_segv3_ls_tiger.out 2>&1 

# 267 270 271 272
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint --ent_cls --joint --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all --ent_cls --joint_all --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_circle_posture_segv3_ls_yak  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/cnn5-64-epoch120.pth >./slurm/seresnet_dve_1_circle_posture_segv3_ls_yak.out 2>&1

#268 273 274 275
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint --ent_cls --joint --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all --ent_cls --joint_all --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_circle_posture_segv3_ls_tiger  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/cnn5-64-epoch120.pth >./slurm/seresnet_dve_1_circle_posture_segv3_ls_tiger.out 2>&1

#269 276 277 278
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_elephant_dve_joint --ent_cls --joint --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_elephant_dve_joint.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_elephant --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_elephant.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_elephant_dve_joint_all --ent_cls --joint_all --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_elephant_dve_joint_all.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_circle_posture_segv3_ls_elephant  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/cnn5-64-epoch120.pth >./slurm/seresnet_dve_1_circle_posture_segv3_ls_ele.out 2>&1

#279 280
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_666 --ent_cls --joint --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --seed 666 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_666 --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --seed 666 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger.out 2>&1

#139 140
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_circle_posture_segv3_ls_tiger_mod  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_1_circle_posture_segv3_ls_tiger_md.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_circle_posture_segv3_ls_yak_mod  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_1_circle_posture_segv3_ls_yak_md.out 2>&1

#170 171
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_2_circle_posture_segv3_ls_yak --version 2  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_2_circle_posture_segv3_ls_yak.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_2_circle_posture_segv3_ls_tiger --version 2  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_2_circle_posture_segv3_ls_yak.out 2>&1
#172 173
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_5_circle_posture_segv3_ls_yak --version 1_5  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_1_5_circle_posture_segv3_ls_yak.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name seresnet_dve_1_5_circle_posture_segv3_ls_tiger --version 1_5  --batch_size 32 --ent_cls --circle --way1_dve --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/resnet-64-epoch120.pth >./slurm/seresnet_dve_1_5_circle_posture_segv3_ls_tiger.out 2>&1

#999 000
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod --num_other 8 --ent_cls --joint_all --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod --num_other 8 --ent_cls --joint_all --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod.out 2>&1
#001 002
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod_stack --num_other 8 --ent_cls --joint_all --stacked --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod_stack.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod_stack --num_other 8 --ent_cls --joint_all --stacked --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod_stack.out 2>&1

#81 80
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_stack  --ent_cls --joint --stacked --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_stack.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_stack  --ent_cls --joint --stacked --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_stack.out 2>&1
#19 20 21
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod1 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 150 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_mod1.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod1 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 150 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_mod1.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_mod1 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 300 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_mod1.out 2>&1

#81 82 83
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_416 --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_416.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_416 --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_416.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_416 --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_416.out 2>&1

#74 75 76
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2  >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled.out 2>&1

#29 30 31
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled2 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 5.0 --dve_loss_scale 0.5 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled2.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled2 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 5.0 --dve_loss_scale 0.5  >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled2.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled2 --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 5.0 --dve_loss_scale 0.5 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled2.out 2>&1

#84 85 86
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test.out 2>&1

#52 53 54
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_416_test --test --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_666.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_416_test --test --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_666.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_416_test --test --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --seed 416 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_666.out 2>&1

#90 91 92
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test_phased --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 --dve_start 20 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test_phased --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 150 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 --dve_start 20 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test_phased --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 --dve_start 20 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test.out 2>&1

#61 62 63
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 150 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test.out 2>&1

#77 78 79
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled2_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing  --dve_loss_scale 0.5  >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled2_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 150 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --dve_loss_scale 0.5  >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_scaled_test.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled2_test_correct --seed 416 --test --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing  --dve_loss_scale 0.5  >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_scaled_test.out 2>&1

#24 -29
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_stack_correct_test --test --num_other 8 --ent_cls --joint_all --stacked --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_stack_correct_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_stack_correct_test --test --num_other 8 --ent_cls --joint_all --stacked --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_stack_correct_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_stack_correct_test --test --num_other 8 --ent_cls --joint_all --stacked --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_stack_correct_test.out 2>&1

# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_test --test --ent_cls --joint  --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_test.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_test --test --ent_cls --joint  --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_test.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_test --test --ent_cls --joint  --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_test.out 2>&1

#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_stack_correct_test_trans --test --test_transfer --num_other 8 --ent_cls --joint_all --stacked --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_stack_correct_test_trans.out 2>&1

#corrected val accuracy, cropped the image, and added test_transfer
#94 
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans --test --test_transfer --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_test_trans.out 2>&1


#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_test_trans --test --test_transfer --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_test_trans.out 2>&1

#102 103
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans --test --test_transfer --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans --test --test_transfer --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans.out 2>&1

#73 74 75
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_test_trans --test --test_transfer --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_test_trans.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_test_trans --test --test_transfer --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_test_trans.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_test_trans --test --test_transfer --ent_cls --batch_size 32 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 200 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_test_trans.out 2>&1


#/home/yinyu/miniconda3/envs/thesis/bin/python test_adapt.py --concat --name tiger_cnn5_v1   -d h_yak -mt tiger -m /home/yinyu/Thesis/animal-reid/model/cnn5_v1_circle_posture_segv3_ls_tiger_416/net_last.pth  --gpu_ids 0 -r /home/yinyu/Thesis/resnet-64-epoch120.pth

#10 11 12...18
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_triplet_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --triplet --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_triplet_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --triplet --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_triplet_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --triplet --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1

# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1


# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_correct_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls  --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_correct_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_correct_test_trans_batch --triplet_sampler --test --test_transfer --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1


#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name tmp --test --test_transfer --num_other 8 --ent_cls --joint_all --batch_size 40 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/tmp.out 2>&1
#09 10 11
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_dve_joint_all_correct_scaled_test_trans_batch --background --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch --background --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_dve_joint_all_correct_scaled_test_trans_batch --background --triplet_sampler --test --test_transfer --ent_cls --joint_all --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_ele_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1

#12 13 14
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch --background  --triplet_sampler --test --test_transfer --ent_cls  --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch --background  --triplet_sampler --test --test_transfer --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_tiger_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch --background --triplet_sampler --test --test_transfer --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 60 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_ele_dve_joint_all_correct_scaled_test_trans_batch.out 2>&1

#50-58
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch.out 2>&1

# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch_666 --seed 666 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch_666 --seed 666 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch_666 --seed 666 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch.out 2>&1



# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch --background --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_dve_joint_correct_scaled_test_batch --background --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_dve_joint_correct_scaled_test_batch --background --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1



#31-36
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch_666  --seed 666  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch_666 --seed 666  --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 >./slurm/cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch_666 --seed 666 --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch.out 2>&1
#
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch_666_unscaled  --seed 666  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing  >./slurm/cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch_666_unscaled --seed 666  --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing  >./slurm/cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch_666_unscaled --seed 666 --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing  >./slurm/cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch.out 2>&1



#40..42

# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch --background  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch --background  --triplet_sampler --test  --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_tiger_correct_test_trans_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch --background --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch.out 2>&1

#600 605
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch_rereun_again --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 140 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_correct_test_batch_rerun --triplet_sampler --test --ent_cls --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 140 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_ele_correct_test_trans_batch.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch_666_rerun --seed 666 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch.out 2>&1

#vit 97 98 99
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name vit_circle_posture_segv3_ls_yak_test_scaled_batch --use_vit --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/vit_circle_posture_ls_yak_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name vit_circle_posture_segv3_ls_tiger_test_scaled_batch --use_vit --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/vit_circle_posture_ls_yak_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name vit_circle_posture_segv3_ls_ele_test_scaled_batch --use_vit --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 180 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/vit_circle_posture_ls_yak_test_batch.out 2>&1
# #resent 00 01 02
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name resnet50_circle_posture_segv3_ls_yak_test_scaled_batch --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/resnet50_circle_posture_segv3_ls_yak_test_scaled_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name resnet50_circle_posture_segv3_ls_tiger_test_scaled_batch  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/resnet50_circle_posture_segv3_ls_yak_test_scaled_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name resnet50_circle_posture_segv3_ls_ele_test_scaled_batch  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 180 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/resnet50_circle_posture_segv3_ls_yak_test_scaled_batch.out 2>&1

# #ablation 04..09

# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_none  --test --ent_cls --use_posture --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_segv3_ablation_none_tiger.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_circle  --test --circle --circle_loss_scale 2.0  --ent_cls --use_posture --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_segv3_ablation_circle.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_circle_pretrain  --test --circle --circle_loss_scale 2.0  --ent_cls --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing --model_path /home/yinyu/Thesis/cnn5-64-epoch120.pth >./slurm/cnn5_v1_segv3_ablation_circle_pretrain.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_circle_dve --joint --circle_loss_scale 2.0 --dve_loss_scale 0.2  --test --circle --ent_cls --use_posture --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 120 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_segv3_ablation_circle_dve.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_circle_batch  --test --triplet_sampler --circle --circle_loss_scale 2.0  --ent_cls --use_posture --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_segv3_ablation_circle_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_segv3_ablation_circle_dve_batch --joint  --triplet_sampler --circle_loss_scale 2.0 --dve_loss_scale 0.2  --test --circle --ent_cls --use_posture --batch_size 30  --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --warm_epoch 3  --label_smoothing >./slurm/cnn5_v1_segv3_ablation_circle_dve_batch.out 2>&1

#step epoch = 60 806
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch_rereun_again2 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 140 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_ele_dve_joint_correct_scaled_test_batch.out 2>&1

#cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch 35,37,38    32..34
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch_100 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_tiger_dve_joint_correct_scaled_test_batch.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name vit_circle_posture_segv3_ls_tiger_test_scaled_batch_80 --use_vit --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/vit_circle_posture_ls_yak_test_batch.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name resnet50_circle_posture_segv3_ls_tiger_test_scaled_batch_80  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 80 -d 0,1 --data_type tiger --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/resnet50_circle_posture_segv3_ls_yak_test_scaled_batch.out 2>&1

#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch_100 --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 100 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_correct_scaled_test_batch_100.out 2>&1
# /home/yinyu/miniconda3/envs/thesis/bin/python train.py --name vit_circle_posture_segv3_ls_yak_test_scaled_batch_80 --use_vit --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/vit_circle_posture_ls_yak_test_batch.out 2>&1
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name resnet50_circle_posture_segv3_ls_yak_test_scaled_batch_80  --triplet_sampler --test --ent_cls  --batch_size 30 --circle --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0  >./slurm/resnet50_circle_posture_segv3_ls_yak_test_scaled_batch.out 2>&1
#17 18
#/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch_complete --background --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type yak --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1
/home/yinyu/miniconda3/envs/thesis/bin/python train.py --name cnn5_v1_circle_posture_ls_ele_dve_joint_correct_scaled_test_batch_complete --background --triplet_sampler --test --ent_cls --joint --batch_size 30 --circle --use_cnn5_v1 --lr 0.01 --total_epoch 80 -d 0,1 --data_type elephant --use_posture --warm_epoch 3  --label_smoothing --circle_loss_scale 2.0 --dve_loss_scale 0.2 >./slurm/cnn5_v1_circle_posture_ls_yak_dve_joint_correct_scaled_test_batch.out 2>&1


cnn5_v1_circle_posture_segv3_ls_yak_dve_joint_all_scaled_attn
seresnet_dve_att_circle_posture_segv3_ls_yak